# Generated by Django 5.1.2 on 2024-10-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
