# Generated by Django 5.1.2 on 2024-10-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_useractionlog_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=10)),
                ("room_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Свободен"),
                            ("booked", "Забронирован"),
                            ("maintenance", "На обслуживании"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
