# Generated by Django 5.1.2 on 2024-10-28 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="room_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="booking.room",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "В ожидании"),
                    ("confirmed", "Подтверждено"),
                    ("cancelled", "Отменено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
