# Generated by Django 5.1.2 on 2024-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("roles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles_in_roles_app", to="auth.permission"
            ),
        ),
    ]
